### ISSUE TITLE
ability to add cloud

### ISSUE THREAD

**Issue by baycarbone** [juju/terraform-provider-juju#105]
Hi,

This is a wishlist issue to enable the addition of clouds to an existing juju controller. This is useful in the case of multi-cloud juju controllers.

Reference: https://juju.is/docs/olm/adding-clouds.

**Comment by sanchezfdezjavier** [comment]
+1 to the wishlist 😄

**Comment by anvial** [comment]
Finally, we introduce the feature to operate with Kubernetes cloud:
https://registry.terraform.io/providers/juju/juju/latest/docs/resources/kubernetes_cloud

Any feedback is welcome!
