### ISSUE TITLE
Ability to add machine constraints to units.

### ISSUE THREAD

**Issue by ale8k** [juju/terraform-provider-juju#109]
Ability to add machine constraints to units.

Currently, I cannot see this possible. The minimum of CpuCores, Mem and RootDisk would be nice.

Thanks.

**Comment by jnsgruk** [comment]
Quote Kristopher T on Mattermost this morning:

> We need to run "juju set-model-constraint mem=70G cores=18 root-disk=1000G"

**Comment by jdkandersson** [comment]
> 



> Quote Kristopher T on Mattermost this morning:
> 
> > We need to run "juju set-model-constraint mem=70G cores=18 root-disk=1000G"
> 
> This is slightly different from machine constraints - @jdkandersson which was it that you were requesting?

Either one works, unit or model

**Comment by juanmanuel-tirado** [comment]
@jdkandersson I will give extra priority to this.

**Comment by jnsgruk** [comment]
@jdkandersson this is being addressed in #118 - if you're feeling adventurous you could clone the branch and test it locally by building the provider per the README :)

**Comment by jdkandersson** [comment]
Thanks for the quick turnaround! I was trying to use it and this is what I did (I not familiar with building terraform providers so I'm probably doing something wrong):

1. Install go `sudo snap install go --classic`
2.Install dependencies `go install`
3. Build the provider `go build -o terraform-provider-juju`
4. Create terraform file:
  ```Terraform
  provider "juju" {}

  resource "juju_model" "githubrunners" {
    name = "prod-github-runner"

    constraints = "mem=70G cores=18 root-disk=1000G"
  }
  ```
5. Run `terraform init` which results in:
```bash
Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/juju...
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/juju: provider registry registry.terraform.io does not have a provider named registry.terraform.io/hashicorp/juju
│ 
│ All modules should specify their required_providers so that external consumers will get the correct providers when using a module. To see which modules are currently depending on hashicorp/juju, run
│ the following command:
│     terraform providers
╵

  ```

**Comment by juanmanuel-tirado** [comment]
You can replicate the folders under `~/.terraform.d/plugins` somewhere else. I have something like `~/my-providers/plugins/registry.terraform.io/juju/juju/1.0.0/linux_amd64/`. And there you copy the binary. Then, you have tu indicate terraform to search there with `terraform init -plugin-dir=my-providers/plugins`. Observe that in this case the version of the controller will be 1.0.0, not 0.4.x. I hope this helps.

**Comment by jdkandersson** [comment]
Ah thank you, that made it possible to use the plugin.

I am encountering an issue where the constraint doesn't seem to be set:

```bash
terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # juju_model.githubrunners will be created
  + resource "juju_model" "githubrunners" {
      + constraints = "mem=70G cores=18 root-disk=1000G"
      + id          = (known after apply)
      + name        = "prod-github-runner"
      + type        = (known after apply)

      + cloud {
          + name   = (known after apply)
          + region = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

juju_model.githubrunners: Creating...
juju_model.githubrunners: Creation complete after 0s [id=6bc79e80-b41c-4776-8e9f-0feaa1871556]

juju get-model-constraints -m prod-github-runner

```

**Comment by juanmanuel-tirado** [comment]
Thanks for testing it. Two comments.
* You're right. The internal representation of constraints in Juju uses Mbytes that is why terraform thinks there was a change. I already knew that but did not add intermediate conversion to have a fix asap.
* About the non-set model constraints. It looks like in some scenarios the `set-model-constraints` call may occur before the model is already up and Juju seems to receive the call with no error. However, the constraints are not set. That is why the constraint may not be set.

We have to provide a fix for both items. Meanwhile, I can only recommend you to use MBytes for constraints, and re-apply in case that constraints are not set. Not the best solution, but it will let you work with constraints until we have a fix committed.

I reopen this issue.
