### ISSUE TITLE
Support for local charms.

### ISSUE THREAD

**Issue by ale8k** [juju/terraform-provider-juju#110]
Hi,

I could not see a way to run local charms.

It would be nice to do something like...

```terraform
resource "juju_application" "this" {
  name = "my-application"

  model = juju_model.development.name

  charm {
    name     = "hello-kubecon"
    channel  = "edge"
    revision = 14
    series   = "trusty"
    charmFromFile = file("${path.module}/my.charm")
  }

  units = 1

  config = {
      ....
  }
}
```

for local development.

Thanks

**Comment by juanmanuel-tirado** [comment]
Hi,

Yes, you're right at this moment we have no option to deploy local charms. We will eventually support them. Meanwhile, I will add this issue to the wishlist.

Thanks,

**Comment by freyes** [comment]
Hi, I got bitten by this limitation, is there any chance that someone can point me out what's needed in the provider to support this?, I would like to try to fix it, but I don't know where I should start.

**Comment by jnsgruk** [comment]
This isn't planned work, and we likely won't merge code to support it. Sadly there is a lot of client side logic required for this, which could perhaps be solved by the future work on Juju's API, but in the mean time you should rely on revisions from the store.

**Comment by freyes** [comment]
> [...]  in the mean time you should rely on revisions from the store.

IMHO, This prevents the use of terraform for development purposes (or makes the adoption more difficult), I suppose the "juju bundle" format will stay around until a developer/contributor can have a complete workflow (edit a charm, pack it, deploy it), unless the plan uses the `null_resource` with a `provisioner` script to run `juju refresh --path ./my.charm` as a post deployment step.
