### ISSUE TITLE
Impossible to operate in a multicloud environment

### ISSUE THREAD

**Issue by sanchezfdezjavier** [juju/terraform-provider-juju#111]
I wasn't super sure on how to name the issue, I can rename it if you find a better name :)
### Terraform Version
```bash
Terraform v1.3.4
on linux_amd64
```

### Affected Resource(s)
The error appears even before creating the resources.

### Terraform Configuration Files
https://github.com/canonical/charmed-magma/blob/44895823ad20bd58be05a13aeb0811e33966b2d6/deployments/charmed-magma-srsRAN/main.tf

### Debug Output
https://gist.github.com/sanchezfdezjavier/c5bed73309a2140250d55dead486d993

### Expected Behavior
It should not complain about connecting to the clients. However, I don't expect to apply all the resources successfully at first.

### Steps to Reproduce
1. Bootstrap an LXD controller
```bash
juju bootstrap localhost lxd-controller
```
2. Create the local k8s cluster by installing `microk8s`
```bash
sudo snap install microk8s --classic
```
3. Copy the kubeconfig

```bash
cd ~/.kube && microk8s config > config
```
```bash
export KUBERNETES_MASTER=~/.kube/config
```

4. Add the k8s cloud to the LXD controller
```bash
juju add-k8s k8s-cloud --controller lxd-controller
```

5. Init Terraform
```bash
terraform init
```

6. Terraform apply
```bash
terraform apply --var="domain=magma.javisf.com" --var="orchestrator_cloud_name=k8s-cloud" --var="agw-srsran_cloud_name=localhost"
```

It should show the plan to apply, and after hitting `yes` it stops at
```bash
Plan: 74 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

juju_model.orchestrator: Creating...
juju_model.agw-srsran: Modifying... [id=829670a4-1af8-4359-80cb-6bd75f049613]
juju_model.agw-srsran: Modifications complete after 0s [id=829670a4-1af8-4359-80cb-6bd75f049613]
```

And throws the error linked in the Debug Output.

### Important Factoids
About my setup:
- Host EC2 instance.
- Juju LXD controller.
- Added one microk8s cloud.
- Two models, one for machine charms, and another one for k8s.

**Comment by sanchezfdezjavier** [comment]
Let me know If I can provide any additional info.

**Comment by juanmanuel-tirado** [comment]
After some research, I can confirm that more than a bug, this is an implementation missing issue. All the logic behind the authorization process in the terraform provider ([here](https://github.com/juju/terraform-provider-juju/blob/0c548cfafbbaac01f12b1c283585ff3162feb02a/internal/juju/models.go#L146)) has been drastically reduced. You can compare it with the current list of steps in juju ([here](https://github.com/juju/juju/blob/a4d540467379a751a7045ea0f17a4624742c70c4/cmd/juju/controller/addmodel.go#L249)). This requires additional development and a new release. 

Thanks for reporting.

**Comment by cderici** [comment]
@sanchezfdezjavier is this still valid? just making sure, thanks!

**Comment by anvial** [comment]
Kubernetes cloud resource is a part of TF provider:
https://registry.terraform.io/providers/juju/juju/latest/docs/resources/kubernetes_cloud
