### ISSUE TITLE
underscore in juju_model and juju_application resources not allowed, but not caught in `plan`

### ISSUE THREAD

**Issue by mthaddon** [juju/terraform-provider-juju#114]
### Terraform Version
```
Terraform v1.3.5
on linux_amd64
+ provider registry.terraform.io/juju/juju v0.4.3
```

### Affected Resource(s)
- juj_model

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    juju = {
      source  = "juju/juju"
      version = "0.4.3"
    }
  }
}
provider "juju" {}

resource "juju_model" "test_model" {
  name = "test_model"
}

resource "juju_application" "test_application" {
  name = "test_application"
  model = juju_model.test_model.name

  charm {
    name = "ubuntu"
  }
}
```

### Debug Output

https://paste.ubuntu.com/p/D7YV7Ryd5n/

### Panic Output

N/A

### Expected Behavior

Either `terraform plan` should warn of not allowed characters, or the `juju_model` resource should support underscores.

### Actual Behavior

See the paste above

### Steps to Reproduce

See the paste above

### Important Factoids
N/A
### References
N/A

**Comment by mthaddon** [comment]
This applies to both the `juju_model` and `juju_application` resources.

**Comment by juanmanuel-tirado** [comment]
No naming control was introduced into the controller in an attempt to minimize the logic inside it. The current policy is to wait for Juju to respond. Said that, I think this could be helpful. I add it to the wishlist. Thanks for reporting!
