### ISSUE TITLE
Migrate to Terraform Plugin Framework

### ISSUE THREAD

**Issue by jnsgruk** [juju/terraform-provider-juju#123]
Hashicorp have released the [Terraform Plugin Framework](https://developer.hashicorp.com/terraform/plugin/framework) which is the evolution from the Terraform Plugin SDK2 on which this project is based.

It doesn't look like a particularly big job, nor is it urgent. There is a migration guide [here](https://developer.hashicorp.com/terraform/plugin/framework/migrating).

We should probably ensure we don't implement anything *new* in the old SDK, at least. There is the ability to mux the two frameworks to allow a gradual migration.

**Comment by hmlanigan** [comment]
There were a number of PRs to make this transition. The last will be https://github.com/juju/terraform-provider-juju/pull/300

**Comment by hmlanigan** [comment]
0.9.0 is being released
