### ISSUE TITLE
Support for importing juju_offer state

### ISSUE THREAD

**Issue by arturo-seijas** [juju/terraform-provider-juju#125]
Hi,

As per the documentation at https://registry.terraform.io/providers/juju/juju/latest/docs/resources/offer there's no way to import the terraform state when it comes to the offers. It is my understanding that this is not yet supported but it would certainly come in handy.

Thank you

**Comment by juanmanuel-tirado** [comment]
You're right, this is not supported yet. I add it to the wishlist.
