### ISSUE TITLE
Error: internal error, Client(5) claimed to return *client.Client but returned *client.ClientV5

### ISSUE THREAD

**Issue by VariableDeclared** [juju/terraform-provider-juju#128]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
```
terraform -v
Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/juju/juju v0.3.1
```
### Affected Resource(s)
Please list the resources as a list, for example:
- juju_application

### Terraform Configuration Files

https://gist.github.com/VariableDeclared/4822b6acebf0a90815fffb03a82512c8

### Debug Output
https://gist.github.com/VariableDeclared/bc38016916cb014ef42aac786bd801d5

### Expected Behavior

Juju model is added and charmed deployed to this model

### Actual Behavior
Terraform failed to provision the applications

### Steps to Reproduce
1. place the k8s tf file
2. terraform init
3. terraform apply (accept/enter yes)

### Important Factoids
Nothing out of the ordinary as far as I know. Running juju 2.9.38

### References
None

**Comment by juanmanuel-tirado** [comment]
It seems you're using an old version of the provider. Could you try with the latest 0.4.3?

**Comment by VariableDeclared** [comment]
thanks! @juanmanuel-tirado that was it :)
