### ISSUE TITLE
Support managing credentials

### ISSUE THREAD

**Issue by jsimpso** [juju/terraform-provider-juju#142]
Hi,

This is a wishlist item to request support for credential management: https://juju.is/docs/olm/manage-credentials

**Comment by juanmanuel-tirado** [comment]
This includes:
* [juju add-credentials](https://juju.is/docs/olm/add-credentials)
* [juju update-credential](https://juju.is/docs/olm/update-a-credential)
* [juju remove-credential](https://juju.is/docs/olm/remove-a-credential)
