### ISSUE TITLE
Support managing SSH keys

### ISSUE THREAD

**Issue by jsimpso** [juju/terraform-provider-juju#145]
Hi,

This is a wishlist item to request SSH key management: https://juju.is/docs/olm/manage-ssh-keys

**Comment by juanmanuel-tirado** [comment]
This includes 
* `[juju add-ssh-key](https://juju.is/docs/olm/juju-add-ssh-key)`
* `[juju remove-ssh-key](https://juju.is/docs/olm/juju-remove-ssh-key)`

**Comment by jameinel** [comment]
Also `juju import-ssh-key`, though I think that is a lower priority

**Comment by mthaddon** [comment]
See https://github.com/juju/terraform-provider-juju/pull/149 for work on this
