### ISSUE TITLE
Add `depends_on` support for Juju application status on initial deploy

### ISSUE THREAD

**Issue by marcoppenheimer** [juju/terraform-provider-juju#163]
### Use Case
I as a charm engineer, want a way to reliably deploy applications and relations sequentially, relating them only after some model state criteria has been met, e.g they have finished setting up (i.e `active/idle`)

### Problem
Currently the only option known to me are bundles, which relate immediately at deploy time, and not after applications are stable.
Looking at this Terraform module, I assumed that `depends_on` would help, but the behavior is similar. As soon as the resources are submitted, they're marked as complete, and any dependent resources are immediately applied.

### Request
Add something similar to the various [`wait_for`](https://www.hashicorp.com/blog/wait-conditions-in-the-kubernetes-provider-for-hashicorp-terraform) attributes in the K8s tf provider, for example for waiting for some user-defined application status, or some action output, or a successful ping to an exposed service on the workload.

**Comment by juanmanuel-tirado** [comment]
Hi @marcoppenheimer thanks for reporting. Yes, you're completely right this would be something really handy. This is already in our wishlist in #116.
