### ISSUE TITLE
Add placement directive for machine resource

### ISSUE THREAD

**Issue by gboutry** [juju/terraform-provider-juju#177]
### Use case

I want to be able to use the placement directives on a machine resource to be able to add manually provisionned machine, or add a container to an existing machine.

### Feature

The placement directive could be implemented either as a String or as a block. I have a preference towards a block implementation, but that would expose the concepts of scope and directive to the end user. Which may not be desired.

#### Example 1
```tf
resource "juju_machine" "machine-a" {
  model      = "my-model"
  series     = "jammy"
  placement {
    scope     = "ssh"
    directive = "ubuntu@my-hostname"
  }
  # or
  placement = "ssh:ubuntu@my-hostname"
}
```
#### Example 2
```tf
resource "juju_machine" "machine-b" {
  model      = "my-model"
  series     = "jammy"
  placement {
    scope     = "lxd"
    directive = juju_machine.machine-a.machine_id
  }
  # or
  placement = "lxd:${juju_machine.machine-a.machine_id}"
}
```

I would be happy to help you implement this feature if you think it's relevant.

**Comment by gboutry** [comment]
An issue that would be problematic with ssh machines, is that you cannot re-add a removed machine on Juju:

```bash
$ juju add-machine ssh:ubuntu@my-host
created machine 2
$ juju remove-machine 2
juju add-machine ssh:ubuntu@my-host

**Comment by juanmanuel-tirado** [comment]
Adding already provisioned machines to Juju is something we want to address during the next development cycle. See #103 for some existing discussions on the topic. You're right, this is an issue that may need some changes in the Juju workflow and deeper discussion.

I leave the issue open. Please, feel free to provide any comments/ideas/requirements.

**Comment by cderici** [comment]
@gboutry Yesterday I wrote a discourse post related to this, I believe that is what you want to do, I'll close this, but feel free to re-open this or a new issue if that's not exactly what you're looking for, here's the post : https://discourse.charmhub.io/t/manual-provisioning-on-aws-using-terraform-juju-provider/10989
