### ISSUE TITLE
Removing a relation defined in terraform causes `terraform plan` to error

### ISSUE THREAD

**Issue by mthaddon** [juju/terraform-provider-juju#186]
### Terraform Version
```
$ terraform -v
Terraform v1.4.3-dev
on linux_amd64
+ provider registry.terraform.io/juju/juju v0.6.0

Your version of Terraform is out of date! The latest version
is 1.4.4. You can update by downloading from https://www.terraform.io/downloads.html
```
### Affected Resource(s)

- juju_integration

### Terraform Configuration Files
```hcl
locals {
  charm_name    = "ubuntu"
  charm_channel = "latest/stable"
}

terraform {
  required_providers {
    juju = {
      source  = "juju/juju"
      version = "0.6.0"
    }
  }
}
provider "juju" {}

resource "juju_model" "relation_test" {
  name = "relation-test"
}

resource "juju_application" "ubuntu" {
  name  = "ubuntu"
  model = juju_model.relation_test.name

  charm {
    name    = local.charm_name
    channel = local.charm_channel
  }

  config = {}

  units = 1
}


resource "juju_application" "telegraf" {
  name = "telegraf"
  model = juju_model.relation_test.name

  charm {
    name = "telegraf"
  }

  units = 0
}

resource "juju_integration" "ubuntu_telegraf" {
  model = juju_model.relation_test.name

  application {
    name = "ubuntu"
  }

  application {
    name = "telegraf"
  }  
}
```

### Debug Output

https://paste.ubuntu.com/p/RqYY8kfpZW/

### Expected Behavior

I would expect `terraform plan` to simply say it's going to re-establish the relation.

### Actual Behavior
`terraform plan` says:
```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: no integrations exist in specified model
│
│   with juju_integration.ubuntu_telegraf,
│   on main.tf line 46, in resource "juju_integration" "ubuntu_telegraf":
│   46: resource "juju_integration" "ubuntu_telegraf" {
│
╵
```

### Steps to Reproduce
See the pastebin above.

**Comment by amandahla** [comment]
Usually, if a resource is removed outside of Terraform, the provider should remove it from the state. 

> When you create something in Terraform but delete it manually, Terraform should gracefully handle it. If the API returns an error when the resource doesn't exist, the read function should check to see if the resource is available first. If the resource isn't available, the function should set the ID to an empty string so Terraform "destroys" the resource in state.


Reference [here](https://developer.hashicorp.com/terraform/tutorials/providers/provider-setup?in=terraform%2Fproviders#implement-read).

In this case, would be better/expected to recreate?

**Comment by juanmanuel-tirado** [comment]
@agileshaw Did you get this issue running the same steps described above?

**Comment by agileshaw** [comment]
@juanmanuel-tirado I was following similar steps indeed. However, I can no longer reproduce the issue with the same steps, so probably the issue was not from the provider itself.

**Comment by juanmanuel-tirado** [comment]
I see. Then I will close the issue. Please, reopen if the problem appears again.  Thanks for reporting.
