### ISSUE TITLE
feature request: application resource

### ISSUE THREAD

**Issue by gboutry** [juju/terraform-provider-juju#194]
### Use case

I want to be able to specify an application resources.

We'll be developing multiple (11) oci images as part of a rework, and being able to specify the oci images in the terraform plan would greatly simplify the work. (Instead of changing the resource after deployment)

### Feature

```tf
resource "juju_application" "service" {
  name  = var.name
  model = var.model
  units = var.scale

  charm {
    name    = var.charm
    channel = var.channel
    series  = "jammy"
  }
  
  resource {
    name      = "service-oci" # name of the resource in metadata.yaml
    oci-image = "my_reachable_registry:32000/my_repo/my_image:v1.1"
  }

  resource {
    name = "traefik-tarball"
    # uploads archive to controller to make it available to deployments
    file = "${path.root}/archives/traefik-2.9.tar.gz"
  }
  
  # No need to specify all of the resources, only the one we need changed
  ... resources ...

}

```

### Comments

I know this is a feature that would ease my development, but may not be desirable.
To make it clear, I only need the OCI part but file resources should be supported.
I am willing to implement the whole feature if this is deemed desirable by the Juju team

**Comment by gboutry** [comment]
Hi @juanmanuel-tirado,

I've tried to implement the feature, and got to a point where it's mostly working.

I have an issue with a specific use case, and can't seem to find how to solve it from juju apis:

The usecase:

Removing the custom `resource` block and then applying. This means reverting to the charm store resource.
```diff
resource "juju_application" "traefik" {
  model = data.juju_model.resource.name
  name  = "traefik"
  charm {
    name    = "traefik-k8s"
    channel = "1.0/stable"
    series  = "focal"
  }

-  resource {
-    name      = "traefik-image"
-    oci_image = "docker.io/traefik:v3.0"
  }
}
```

Do you have any pointers on how to revert a charm resource to its store version ?

**Comment by gboutry** [comment]
Thanks for the pointers @juanmanuel-tirado. Indeed, it looks like making an upload request providing the pending ID should be the right way to do it. But I have already tried to re-create the resource through `AddPendingResources` but I always get this error message:
```
listing resources for charm "ch:amd64/focal/traefik-k8s-110": Instance key 'ed8e5885-830c-46b2-8c34-e15c6d3eb055' invalid 'base' in 'download' for charm_id=9jjrT5C28rJhnK4yaGUEM51nQvWR26YG name=traefik-k8s
```

It looks like you cannot add pending resources when the application is already deployed.

(Note, when the application is not deployed, I can add pending resources without issue)

**Comment by juanmanuel-tirado** [comment]
I had a discussion with other juju members and I can confirm that there is not such a thing as a `RemovePendingResources`. And you're right every added resource will live as long as the application is deployed. That is simply not in the juju workflow. With this limitation I would force a `remove-application` every time the `resource` is updated.

**Comment by gboutry** [comment]
I wanted to avoid that, but it looks like it's only way, thank you for confirming!

**Comment by dparv** [comment]
+1

**Comment by orfeas-k** [comment]
Any news on that? It would be a good-to-have for testing charms with different images

**Comment by hmlanigan** [comment]
0.14.0 supports resources specified by revision number or providing an oci-image url. We will not support upload of a local file resource.
