### ISSUE TITLE
terraform reports region value update which doesn't get resolved on apply.

### ISSUE THREAD

**Issue by swalladge** [juju/terraform-provider-juju#209]
Terraform reports update to model that doesn't get resolved after applying.  It always wants to remove the region key, although it was not included in the tf file.

### Terraform Version

```
Terraform v1.4.6
on linux_amd64
```

### Affected Resource(s)

- `juju_model`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    juju = {
      version = "~> 0.7.0"
      source  = "juju/juju"
    }
  }
}


provider "juju" {}

resource "juju_model" "terraform" {
  name = "terraform"

  cloud {
    name   = "localhost"
  }
}
```

### Panic Output

NA

### Expected Behavior

no changes reported

### Actual Behavior

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # juju_model.terraform will be updated in-place
  ~ resource "juju_model" "terraform" {
        id         = "b86dbd3b-07ec-4283-8019-dc99903142ac"
        name       = "terraform"
        # (3 unchanged attributes hidden)

      ~ cloud {
            name   = "localhost"
          - region = "localhost" -> null
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`
3. `terraform apply`

Note that the change is never resolved.

### Important Factoids

- lxd localhost cloud, juju 3.1.2

### References

NA

**Comment by juanmanuel-tirado** [comment]
@swalladge this looks like a bug to investigate.

Could you please use the bug report template like in #184 ?
