### ISSUE TITLE
Add a container machine

### ISSUE THREAD

**Issue by agileshaw** [juju/terraform-provider-juju#219]
The provider doesn't have the ability to add a container to a pre-existing machine or provisioning a new machine hosting a container. It would be nice to have these features added.

**Comment by cderici** [comment]
I'm not entirely sure what this means, can you give an example scenario and how you'd do it with, say, juju cli? Thanks!

**Comment by agileshaw** [comment]
Sure, here are the corresponding juju Cli command:
```bash
# Start a LXD container on a new machine instance and add both as machines. 
juju add-machine lxd

# Create a container on machine 4 and add it as a machine.
juju add-machine lxd:4
```

**Comment by cderici** [comment]
Ah I see, so it'd be an extension of the work in #212, yeah we can do that👍

**Comment by hmlanigan** [comment]
Added in #381
