### ISSUE TITLE
Import SSH keys 

### ISSUE THREAD

**Issue by agileshaw** [juju/terraform-provider-juju#220]
In addition to support adding SSH key with a string literal, it would be great if the provider can import SSH keys from LP or GH (`juju import-ssh-key`). 

Related to: https://github.com/juju/terraform-provider-juju/issues/145

**Comment by juanmanuel-tirado** [comment]
This should be an enhancement of the existing support for SSH keys.

**Comment by hmlanigan** [comment]
This feature was introduced in 0.5.0.

**Comment by skatsaounis** [comment]
@hmlanigan I would like to revive this issue and potentially re-open it. It seems that there was some confusion back then. The import functionality is not covered by the existing `juju_ssh_key`. Importing from GitHub or Launchpad is a very interesting addition. It could be done with the same resource and a XOR string field `source`. So if `payload` is set, create the key and if `source` is set and it is valid, startsWith `gh:` or `lp:`, then import the key.

cc: @SimoneDutto 

```bash
juju import-ssh-key --help

Usage: juju import-ssh-key [options] <lp|gh>:<user identity> ...

Summary:
Adds a public SSH key from a trusted identity source to a model.
```
