### ISSUE TITLE
Updating a charm through Terraform doesn't update resources

### ISSUE THREAD

**Issue by omar-selo** [juju/terraform-provider-juju#278]
### Description

Incrementing revision number of a charm in Terraform configuration. Then apply that configuration. This updates the deployed charm. However the resources related to this charm are not updated. That means that there is no way to use terraform to fully update a charm. Note that using `juju refresh` works and updates the resources too.

### Urgency

Casually reporting

### Terraform Juju Provider version

0.7.0

### Terraform version

v1.5.5

### Reproduce / Test

```shell
Just `terraform apply` but with updated revision in configuration
```

### Notes & References

MM chat https://chat.charmhub.io/charmhub/pl/dzgzs4yg67rpdfk1zomnzoqb8a

**Comment by mthaddon** [comment]
We've also noticed this and were about to report the same bug.

**Comment by hemanthnakkina** [comment]
I am testing this with v0.9.1 on juju 3.1/stable and got the following error

Unable to update application resource, got error: base required for charm-hub charms (bad request)

Terraform plan used:
```
terraform {

  required_providers {
    juju = {
      source  = "juju/juju"
      version = "= 0.9.1"
    }
  }

}

provider "juju" {}

data "juju_model" "test" {
  name = "test"
}

resource "juju_application" "this" {
  name  = "ubuntu"
  model = data.juju_model.test.name
  units = 1

  charm {
    name     = "jameinel-ubuntu-lite"
    channel  = "latest/stable"
    revision = var.revision
    series   = "focal"
  }
}

variable revision {
  description = "Charm revision"
  default     = 9
}
```
