### ISSUE TITLE
Application resource plans can fail with "Charm Already Exists", if another application has loaded that charm to the controller before.

### ISSUE THREAD

**Issue by moisesbenzan** [juju/terraform-provider-juju#296]
### Description

On resource creation, a TF plan can fail with `charm <charm_name_and_revision> already exists` error if another application in the same deployment has already uploaded the charm to the Juju controller before this new application gets deployed.

The Juju TF provider should handle these cases gracefully and continue the operation.

Relevant logs attached below, contact the SQA team for more details.

[fce_deploy_sunbeam_370_console.out.txt](https://github.com/juju/terraform-provider-juju/files/12515183/fce_deploy_sunbeam_370_console.out.txt)

Very similar to: https://github.com/juju/terraform-provider-juju/issues/272

### Urgency

Blocker for our release

### Terraform Juju Provider version

0.7.0

### Terraform version

1.5.6-1

### Reproduce / Test

```shell
1. Create a TF plan that relates to a juju controller with 2 models.
2. Create a Juju Application to the first model, using a charm resource, in this case,`ch:amd64/jammy/mysql-router-k8s-46`.
3.Create a Juju Application to the second model. Be sure to use the same charm series and revision.
4. terraform init && terraform apply
```

### Debug/Panic Output

```shell
with module.mysql.juju_application.mysql[1],
  on modules/mysql/main.tf line 28, in resource "juju_application" "mysql":
  28: resource "juju_application" "mysql" {


Error: charm "ch:amd64/jammy/mysql-router-k8s-46" already exists (already exists)
```

**Comment by hmlanigan** [comment]
@moisesbenzan, I am unable to reproduce this bug with provider 0.8.0, nor 0.7.0 with the following plan

```
terraform {
  required_providers {
    juju = {
      version = "0.7.0"
      source  = "juju/juju"
    }
  }
}

provider "juju" {
}

resource "juju_model" "one" {
  name = "east-two-two"
}

resource "juju_model" "two" {
  name = "east-one-one"
}

resource "juju_application" "one" {
  model = juju_model.one.name
  name = "one-mysql"
  charm {
    name = "mysql-router-k8s"
    channel = "8.0/candidate"
    series = "jammy"
  }
}

resource "juju_application" "two" {
  model = juju_model.two.name
  name = "one-mysql"
  charm {
    name = "mysql-router-k8s"
    channel = "8.0/candidate"
    series = "jammy"
  }
}
```

**Comment by hmlanigan** [comment]
also working is deploy of same charm with two different application names in the same model. #329
