### ISSUE TITLE
Credential name doesn't work since 0.9.0

### ISSUE THREAD

**Issue by gboutry** [juju/terraform-provider-juju#310]
### Description

juju_model resource is breaking with value `sunbeam-microk8s-creds` (valid credentials registered in juju controller)

### Urgency

Blocker for our release

### Terraform Juju Provider version

0.9.0

### Terraform version

1.3.7

### Terraform Configuration(s)

https://github.com/canonical/sunbeam-terraform/

### Reproduce / Test

```shell
Create a machine controller
Add a microk8s cloud to the controller
Reference its credentials in sunbeam-terraform
terraform init
terraform apply
```

### Debug/Panic Output

```shell
When applying changes to juju_model.sunbeam, provider                                                                                                                                   
                    "provider[\"registry.terraform.io/juju/juju\"]" produced an unexpected new                                                                                                              
                    value: .credential: was cty.StringVal("sunbeam-microk8s-creds"), but now                                                                                                                
                    cty.StringVal("sunbeam-microk8s/micro1.project.serverstack/sunbeam-microk8s-creds").
```

### Notes & References

This is a regression introduced in `0.9.0`.
Deploying with `0.8.0` works fine.

**Comment by hmlanigan** [comment]
@gboutry can you please point to where `juju_model.sunbeam` is defined in the GitHub repo provided.

**Comment by gboutry** [comment]
Of course: https://github.com/canonical/sunbeam-terraform/blob/8ec04e0dc6d76fa3ea406c5a23bb88d349a2101a/main.tf#L38C1-L38C1

**Comment by hmlanigan** [comment]
@gboutry my understanding is that sunbeam hardcodes the version of the terraform provider used by pulling it into the snap, please confirm.

**Comment by gboutry** [comment]
At snap build time, snapcraft will pull the providers respecting the plans' constraints.

We don't set upper constraints on terraform provider and 0.9.0 got pulled in our latest edge.

**Comment by gboutry** [comment]
This [job](https://github.com/canonical/sunbeam-terraform/actions/runs/6099619222/job/16744357779) failed because credentials `""` got translated to `microk8s/admin/microk8s`

Error message:
```
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to juju_model.sunbeam, provider
│ "provider[\"registry.terraform.io/juju/juju\"]" produced an unexpected new
│ value: .credential: was cty.StringVal(""), but now
│ cty.StringVal("microk8s/admin/microk8s").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
```
