### ISSUE TITLE
`terraform apply` fails if there are no registered controllers

### ISSUE THREAD

**Issue by Osama-Kassem** [juju/terraform-provider-juju#340]
### Description

After upgrading from v0.8 to v0.9, I noticed that `terraform apply` failed with the error:
```
╷
│ Error: Unable to get live controller data
│ 
│   with provider["registry.terraform.io/juju/juju"],
│   on main.tf line 10, in provider "juju":
│   10: provider "juju" {}
│ 
│ the Juju CLI could not be accessed
╵
```

Weirdly enough, the failure only happened when the job was running on Jenkins, and never when ran directly on a local machine.

After some digging in the code, I noticed that the error `the Juju CLI could not be accessed` originates from this method which populates the local controller config

https://github.com/juju/terraform-provider-juju/blob/6f0127f50c0c2a1d5f24ed71743c7ea0e5f4eb84/internal/juju/utils.go#L58-L68

https://github.com/juju/terraform-provider-juju/blob/6f0127f50c0c2a1d5f24ed71743c7ea0e5f4eb84/internal/juju/utils.go#L72-L80

The local config is populated by calling `juju show-controller --show-password --format=json`.

Well, what would happen if there were no registered controllers, and everything was passed through env vars? How does this `errors.New("the Juju CLI could not be accessed")` get handled?

https://github.com/juju/terraform-provider-juju/blob/6f0127f50c0c2a1d5f24ed71743c7ea0e5f4eb84/internal/provider/provider.go#L40-L53

Well, it doesn't :(
If there is no local config, then the provider does not attempt to read the config in the env vars.

### Urgency

Blocker for our release

### Terraform Juju Provider version

0.9.0, 0.10.0

### Terraform version

v1.6.3

### Reproduce / Test

```shell
Run `terraform apply` on a machine where no Juju controllers are registered
```

**Comment by hmlanigan** [comment]
Looking for live registered controllers is the last fall back. It means that the plan did not have the controller info needed, nor did the env var exist.
