### ISSUE TITLE
Add Placement to the Machine resource schema

### ISSUE THREAD

**Issue by amandahla** [juju/terraform-provider-juju#381]
This issue is for reviewing the addition of `placement` to the Machine resource to fix the issue #347

### WIP PR
https://github.com/juju/terraform-provider-juju/pull/378

### Docs

# juju_machine (Resource)

A resource that represents a Juju machine deployment. Refer to the juju add-machine CLI command for more information and limitations.

## Example Usage

resource "juju_machine" "this_machine" {
  model       = juju_model.development.name
  base        = "ubuntu@22.04"
  name        = "this_machine"
  constraints = "tags=my-machine-tag"
}

### Required

- `model` (String) The Juju model in which to add a new machine.

### Optional

- `base` (String) The operating system to install on the new machine(s). E.g. ubuntu@22.04.
- `constraints` (String) Machine constraints that overwrite those available from 'juju get-model-constraints' and provider's defaults.
- `disks` (String) Storage constraints for disks to attach to the machine(s).
- `name` (String) A name for the machine resource in Terraform.
- `placement` (String) The  operating system container type to install on the new machine(s).
- `private_key_file` (String) The file path to read the private key from.
- `public_key_file` (String) The file path to read the public key from.
- `series` (String, Deprecated) The operating system series to install on the new machine(s).
- `ssh_address` (String) The user@host directive for manual provisioning an existing machine via ssh. Requires public_key_file & private_key_file arguments.

### Read-Only

- `id` (String) The ID of this resource.
- `machine_id` (String) The id of the machine Juju creates.

## Import

Import is supported using the following syntax:

```shell
# Machines can be imported using the format: `model_name:machine_id:machine_name`.
# The value of machine_id is the Juju Machine ID. machine_name is an optional 
# name you can define in Terraform for the machine. It is not used in Juju.
# Here is an example to import a machine from the development model with 
# machine ID 1 and a name "machine_one":
$ terraform import juju_machine.machine_one `development:1:machine_one`
```

**Comment by hmlanigan** [comment]
@amandahla,

 Thank you for helping me refine this process as the first to go thru it. I plan to add an issue template for this process based on our conversations here. 

Can you please specify what Validators, PlanModifiers, and options you plan to have the new Placement StringAttribute use? Will it be optional, sensitive, and/or computed? Will it have a default?

**Comment by amandahla** [comment]
Sorry for the delay. Here are the answers:

- Validator: 
```
stringvalidator.ConflictsWith(path.Expressions{
						path.MatchRoot(ConstraintsKey),
					}...)
```
- PlanModifiers: 
```
stringplanmodifier.RequiresReplaceIfConfigured()
stringplanmodifier.UseStateForUnknown()
```
- Required: False
- Optional: True
- Sensitive: False
- Computed: False
- Default: Empty

**Comment by hmlanigan** [comment]
@amandahla  A second Validator is also needed (SSHAddressKey):
``` code
 stringvalidator.ConflictsWith(path.Expressions{
                                      path.MatchRoot(SSHAddressKey),
                                      path.MatchRoot(ConstraintsKey),
                        	}...)
```

I'd like to be explicit in case the ConstraintsKey attributes change.

Approved with the above addition.

**Comment by hmlanigan** [comment]
This change has been released.
