### ISSUE TITLE
Ordering of charm upgrade and config change

### ISSUE THREAD

**Issue by mthaddon** [juju/terraform-provider-juju#389]
### Description

Currently there seems to be no ordering in terms of applying config changes vs. charm upgrades in a `terraform apply`. This means that if you're setting a new config option, it can fail.

### Urgency

Casually reporting

### Terraform Juju Provider version

0.10.1

### Terraform version

v1.5.7

### Terraform Configuration(s)

```terraform
See https://github.com/juju/terraform-provider-juju/issues/184 for details. Only the juju provider version has changed.
```

### Reproduce / Test

```shell
1. Deploy a charm with a revision that doesn't include a configuration option
2. `terraform apply` a charm upgrade that applies the new config at the same time
```

### Debug/Panic Output

```shell
https://pastebin.ubuntu.com/p/ncp6NBpjT9/
```

**Comment by anvial** [comment]
Fix Committed. It will be released in 0.11.0
