### ISSUE TITLE
Allow `force` application removal

### ISSUE THREAD

**Issue by agileshaw** [juju/terraform-provider-juju#396]
### Requirements

```terraform
I would like to be able to "force" remove an application with the provider
```

### Urgency

It would save from a weird workaround

### Notes & References
Currently when removing an application which is in non-`active` status with the provider, the application will not be fully clean-up; instead it will be left with `terminated lost`. It would be nice if the provider allows user to specify a `force` argument to achieve the same result as `juju remove-application <app_name> --force`

**Comment by hmlanigan** [comment]
The juju client `--force` flag does not fit into the terraform approach to doing things and should remain in the juju client world.

In general the `--force` flag is dangerous and is not recommended for use. It may have unintended side effects such as artifacts left behind within the juju database.

For juju itself, we are looking for ways to improve the destroy and remove experience where juju can do something. For example, ignore hook errors might help in some scenarios.
