### ISSUE TITLE
Add the option to support --to subnet=XXX directive

### ISSUE THREAD

**Issue by dparv** [juju/terraform-provider-juju#432]
### Requirements

```terraform
On Azure and AWS it should be possible to specify the subnet to deploy applications or add machine with this --to directive: https://juju.is/docs/juju/placement-directive#heading--subnet
```

### Urgency

Casually wishlisting

**Comment by hmlanigan** [comment]
@dparv Have you tried using the placement attribute of an application resource? 

There is a bug in juju itself as you found, https://bugs.launchpad.net/juju/+bug/2056501. Please try with a juju 3.1 or 3.2 controller.

**Comment by dparv** [comment]
Closing as ^ works!
