### ISSUE TITLE
Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by Gmerold** [juju/terraform-provider-juju#445]
### Description

Hello Team,

Recently I started getting this strange error when trying to deploy my product as part of my team's CI pipeline:
```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.sdcore.module.self-signed-certificates.juju_application.self-signed-certificates,
│ provider "provider[\"registry.terraform.io/juju/juju\"]" produced an
│ unexpected new value: .charm[0].channel: was cty.StringVal("beta"), but now
│ cty.StringVal("latest/beta").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```
I'm not sure where does it get the `latest/beta` reference from, because we're not using it anywhere in our Terraform files.
My Juju version is `3.4.2`.
Last working run was using Juju `3.4.0`. The version of the Terraform Juju Provider hasn't changed.

BR,
Bartek

### Urgency

Annoying bug in our test suite

### Terraform Juju Provider version

0.11.0

### Terraform version

Terraform v1.7.5-dev installed with Snap

### Terraform Configuration(s)

```terraform
resource "juju_model" "sdcore" {
  name = "sdcore"
}

module "sdcore-router" {
  source = "git::https://github.com/canonical/sdcore-router-k8s-operator//terraform"

  model_name = juju_model.sdcore.name
  depends_on = [juju_model.sdcore]
}

module "sdcore" {
  source = "git::https://github.com/canonical/terraform-juju-sdcore-k8s//modules/sdcore-k8s"

  model_name = juju_model.sdcore.name
  create_model = false
  deploy_cos = true

  depends_on = [module.sdcore-router]
}

module "gnbsim" {
  source = "git::https://github.com/canonical/sdcore-gnbsim-k8s-operator//terraform"

  model_name = juju_model.sdcore.name
  depends_on = [module.sdcore-router]
}

resource "juju_integration" "gnbsim-amf" {
  model = juju_model.sdcore.name

  application {
    name     = module.gnbsim.app_name
    endpoint = module.gnbsim.fiveg_n2_endpoint
  }

  application {
    name     = module.sdcore.amf_app_name
    endpoint = module.sdcore.fiveg_n2_endpoint
  }
}

resource "juju_integration" "gnbsim-nms" {
  model = juju_model.sdcore.name

  application {
    name     = module.gnbsim.app_name
    endpoint = module.gnbsim.fiveg_gnb_identity_endpoint
  }

  application {
    name     = module.sdcore.nms_app_name
    endpoint = module.sdcore.fiveg_gnb_identity_endpoint
  }
}
```

### Reproduce / Test

```shell
terraform init
terraform apply
```

**Comment by Aflynn50** [comment]
Hey @Gmerold, we are planning to add a validator to the channel field that checks that this value consists of a track and a risk to go out in version 12. This class of bugs is caused by the fact that juju resolves the default track itself when it is missing and this then creates an inconsistency when comparing the plan with the state.

Since terraform plans should give reproducible deployments it makes sense that we should ask user to provide the track too.

**Comment by Gmerold** [comment]
Yeah, I thought that would be the reason. 
Thanks for your comment @Aflynn50. I'm looking forward to version 12 of the provider!
