### ISSUE TITLE
juju_machine should allow both placement and constraints

### ISSUE THREAD

**Issue by arif-ali** [juju/terraform-provider-juju#476]
### Description

Following the PR #378 of the placement addition in 0.11.0, and came to test this today, but have come to another issue. We should be able to appliy a constraint and a placement, but the provider does not allow us to do this

### Urgency

Blocker for our release

### Terraform Juju Provider version

0.12.0

### Terraform version

1.8.2

### Terraform Configuration(s)

```terraform
resource "juju_machine" "ceph-mon-1" {
  model = juju_model.cpe-focal.name
  placement = join(":",["lxd",juju_machine.all_machines["101"].machine_id])
  constraints = "spaces=oam,ceph-access,ceph-replica"
}
```

### Reproduce / Test

```shell
❱❱❱ juju add-machine lxd:34 --constraints="spaces=oam,ceph-access,ceph-replica"
created container 34/lxd/8

The above extract from terraform gives me the following error


╷
│ Error: Invalid Attribute Combination
│ 
│   with juju_machine.ceph-mon-1,
│   on 05-ceph.tf line 35, in resource "juju_machine" "ceph-mon-1":
│   35:   placement = join(":",["lxd",juju_machine.all_machines["101"].machine_id])
│ 
│ Attribute "constraints" cannot be specified when "placement" is specified
```
```


### Debug/Panic Output

```shell
n/a
```

### Notes & References

n/a

**Comment by hmlanigan** [comment]
@arif-ali

In your example juju will attempt to use those spaces for the container if they are available on the host machine, however will continue if not and use the spaces available to the host machine as a fallback. For spaces, juju does not treat space constraints exactly the same as when creating a machine. 

The example below is a bit more straight forward:
```tf
resource "juju_machine" "ceph-mon-1" {
  model = juju_model.cpe-focal.name
  placement = join(":",["lxd",juju_machine.all_machines["101"].machine_id])
  constraints = "mem=10G"
}
```

**Comment by arif-ali** [comment]
If I don't add any constraints, then the lxd fails to deploy, and get the following from `juju status --format json`

```json
      "7/lxd/0": {
        "juju-status": {
          "current": "down",
          "message": "agent is not communicating with the server",
          "since": "02 May 2024 20:19:34+01:00"
        },
        "instance-id": "pending",
        "machine-status": {
          "current": "provisioning error",
          "message": "no obvious space for container \"7/lxd/0\", host machine has spaces: \"admin\", \"ceph-access\", \"ceph-replica\", \"external\", \"internal\", \"oam\", \"overlay\"",
          "since": "02 May 2024 20:19:34+01:00"
        },
        "modification-status": {
          "current": "idle",
          "since": "02 May 2024 19:59:35+01:00"
        },
        "series": "focal"
      },
```

adding the constraint causes the original issue

**Comment by arif-ali** [comment]
> @arif-ali
> 
> In your example juju will attempt to use those spaces for the container if they are available on the host machine, however will continue if not and use the spaces available to the host machine as a fallback. For spaces, juju does not treat space constraints exactly the same as when creating a machine.
> 
> The example below is a bit more straight forward:
> 
> ```terraform
> resource "juju_machine" "ceph-mon-1" {
>   model = juju_model.cpe-focal.name
>   placement = join(":",["lxd",juju_machine.all_machines["101"].machine_id])
>   constraints = "mem=10G"
> }
> ```

Even with `constraints="mem=10G"` doesn't work unfortunately

```hcl
 resource "juju_machine" "ceph-mon-1" {
  model = juju_model.cpe-focal.name
  placement = join(":",["lxd",juju_machine.all_machines["101"].machine_id])
#  constraints = "spaces=oam,ceph-access,ceph-replica"
  constraints = "mem=10G"
}
```

```
╷
│ Error: Invalid Attribute Combination
│ 
│   with juju_machine.ceph-mon-1,
│   on 05-ceph.tf line 35, in resource "juju_machine" "ceph-mon-1":
│   35:   placement = join(":",["lxd",juju_machine.all_machines["101"].machine_id])
│ 
│ Attribute "constraints" cannot be specified when "placement" is specified
╵
```

**Comment by arif-ali** [comment]
I removed the [line](https://github.com/juju/terraform-provider-juju/blob/main/internal/provider/resource_machine.go#L184), compiled the provider, and used it locally, and now for me it works as expected. I have managed to deploy lxd/kvm machines successfully and attach them to applications similar to what I was originally expecting

**Comment by cderici** [comment]
@arif-ali sounds like the placement conflicts can be relaxed, can you open a PR with your change and qa steps so we can take a closer look at it? Thanks!

**Comment by hmlanigan** [comment]
@cderici, @arif-ali - I'm working on this bug already. It's in the milestone for 0.13.0. It also has a jira card.

**Comment by cderici** [comment]
> @cderici, @arif-ali - I'm working on this bug already. It's in the milestone for 0.13.0. It also has a jira card.

Sorry that's my mistake, I didn't realize @hmlanigan was on this, you may safely ignore my message 👍
