### ISSUE TITLE
Schema: Generic JAAS Resource Access

### ISSUE THREAD

**Issue by kian99** [juju/terraform-provider-juju#531]
# Description 
Requesting schema change to add a generic schema that can be instantiated for various resources and used to grant/revoke permissions. This schema change is part of work to allow the Juju Terraform provider to use JAAS-specific APIs. See more about JAAS [here](https://canonical-jaas-documentation.readthedocs-hosted.com/en/latest/).

Note that this change also depends on a new resource for `groups` which will be proposed in a separate issue.

## Example plan

``` terraform
terraform {
  required_version = ">= x.x.x"
  required_providers {
    juju = {
      source  = "juju/juju"
      version = "~> 0.10.1"
    }
  }
}

provider "juju" {
  controller_addresses = "https://jaas.canonical.com"
  client_id            = "jujuclientid"
  client_secret        = var.client_secret
}

resource "juju_model" "this" {
  name = "development"

  cloud {
    name   = "aws"
    region = "eu-west-1"
  }

  config = {
    logging-config              = "<root>=INFO"
    development                 = true
    no-proxy                    = "jujucharms.com"
    update-status-hook-interval = "5m"
  }
}

resource "juju_jaas_group" "test_group" {
  name = "my-favorite-group"
}

resource "juju_jaas_access_group" "test_group_members" {
  group_name = juju_jaas_group.test_group.name
  access     = "member"
  users      = ["bob@gmail.com", "alice@gmail.com"]
}

resource "juju_jaas_access_model" "this_access_writers" {
  model_uuid   = juju_model.this.uuid
  access = "write"
  users  = ["kian.parvin@gmail.com", "foo@gmail.com"]
  groups = [juju_jaas_group.test_group.uuid]
  service_accounts = ["7dd52cd6-eda6-4b2f-8d7f-c907cb5927c6"]
}
```

## Schema
``` go
	"<ref.Type>": schema.StringAttribute{
		Description: ref.Type + " of the " + ref.resourceTag + " resource",
		Required:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.RequiresReplace(),
		},

	},
	"access": schema.StringAttribute{
		Description: "Access level",
		Required:    true,
		Validators:  []validator.String{},
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.RequiresReplace(),
		},

	},
	"users": schema.SetAttribute{
		ElementType: types.StringType,
		Optional:    true,
		Validators:  []validator.Set{emailValidator},
	},
	"groups": schema.SetAttribute{
		ElementType: types.StringType,
		Optional:    true,
		Validators:  []validator.Set{groupNameValidator},
	},
	"service_accounts": schema.SetAttribute{
		ElementType: types.StringType,
		Optional:    true,
		Validators:  []validator.Set{serviceAccountValidator},
	},
```

Above, the first field `"<ref.Type>"` is intended to illustrate that the schema is variable depending on which object implements the schema. Some examples could include:
- `model_uuid`
- `applicationoffer_uuid`
- `cloud_name`
Some resources like Juju Clouds do not have an UUID but rather only have a unique name.

## Validation

To prevent users from using these resources without JAAS, the following blueprint for a validator is proposed.
```
func (r *genericJAASAccessModelResource) ConfigValidators(ctx context.Context) []resource.ConfigValidator {
	return []resource.ConfigValidator{
		RequiresJAASValidator{Client: r.client},
	}
}
```

## Explanation

The reason the resource is "generic" is because the JAAS API allows permissions to be managed through a single API endpoint and the only change between resources is the tag provided i.e. "model" or "cloud" or "applicationoffer", etc. 

The provider can internally instantiate a generic resource access object with a different tag and then permissions don't require extra code when new resources are added. The full list of resources that intend to use the generic JAAS access schema include:
- `juju_jaas_access_model`
- `juju_jaas_access_applicationoffer`
- `juju_jaas_access_cloud`
- `juju_jaas_access_controller`
- `juju_jaas_access_group`
- `juju_jaas_access_serviceaccount`

## Naming preferences
- Resource Name: Is `juju_jaas_access` the preferred naming scheme?
- Schema attribute: Is the name `uuid` acceptable for the schema?

### Urgency

Casually wishlisting

### Notes & References

[Internal specification](https://docs.google.com/document/d/1X664wYxU-4fEd1IdRwp0KOUXd8JG_hdw7JzoZ4UzA_Q/edit)
Depends on https://github.com/juju/terraform-provider-juju/issues/531

One thing I noticed while writing this is that we use a group's name as reference instead of the group's UUID. This doesn't make a big difference but it means that if you change a group's name then some permissions will be updated, if we used the UUID and you update the name, nothing changes.

**Comment by hmlanigan** [comment]
`uuid` in the generic resource access schema is ambiguous, should be `model_uuid`.

If `groups = [juju_jaas_group.test_group.name]` in the generic resource access example (and schema) , why give `juju_jaas_group` resource a uuid?

How can a group have an access level, but then be included in a different generic resource access with a different access level? Same for service accounts. I'm seeing how generic resource can be useful for all but `juju_jaas_access_group` and
`juju_jaas_access_serviceaccount`. There seems to be conflict between the access level of a group or service account and the things that can have access levels: models, clouds, application offers and controllers.

**Comment by hmlanigan** [comment]
> Just to clarify, I assume you mean why add a UUID to the schema for groups as defined in https://github.com/juju/terraform-provider-juju/issues/532? It would overall be better if I switched the group reference to use a UUID rather than a name. I will edit this above, so that group references are now

Yes

**Comment by kian99** [comment]
Right, I've switched the groups field to expect a UUID so now it should make more sense.

**Comment by hmlanigan** [comment]
Approved.
