### ISSUE TITLE
Schema: JAAS Group

### ISSUE THREAD

**Issue by kian99** [juju/terraform-provider-juju#532]
### Description

Requesting schema change to add a group resource that will be used as part of permission management. 

Groups are entities that can be given permission to Juju resources. Users can be added to groups. Groups can also be added to other groups. To see how users can be added to groups, see #531.

This schema change is part of work to allow the Juju Terraform provider to use JAAS-specific APIs. See more about JAAS [here](https://canonical-jaas-documentation.readthedocs-hosted.com/en/latest/).

### Example Plan

``` terraform
terraform {
  required_version = ">= x.x.x"
  required_providers {
    juju = {
      source  = "juju/juju"
      version = "~> 0.10.1"
    }
  }
}

provider "juju" {
  controller_addresses = "https://jaas.canonical.com"
  client_id            = "jujuclientid"
  client_secret        = var.client_secret
}

resource "juju_jaas_group" "test_group" {
  name = "my-group"
}
```

### Schema

``` go
	"name": schema.StringAttribute{
		Description: "Name of the group",
		Required:    true,
		Validators:  []validator.Set{groupNameValidator},

	},
	"uuid": schema.StringAttribute{
		Description: "UUID of the group",
		Computed: true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	},
```

### Urgency

Casually wishlisting

### Notes & References

[Internal Specification](https://docs.google.com/document/d/1X664wYxU-4fEd1IdRwp0KOUXd8JG_hdw7JzoZ4UzA_Q/edit)

**Comment by hmlanigan** [comment]
This schema will create a group with the given name only. How do you add users to the group as mentioned in the description?

**Comment by kian99** [comment]
Adding users to the group is described in the #531. Would you like to see more info on that here?

**Comment by hmlanigan** [comment]
You wouldn't add users AND set the access within one resource. 

I'd expect to have a group with users, then set the group access in a different resource. One resource defines a group, the other defines the group access e.g.:

``` terraform
resource "juju_jaas_group" "test_group" {
  name = "my-favorite-group"
  users = ["bob@gmail.com", "alice@gmail.com"]
}

resource "juju_jaas_access_group" "test_group_members" {
  group_name = juju_jaas_group.test_group.uuid
  access     = "member"
}
```

**Comment by kian99** [comment]
>You wouldn't add users AND set the access within one resource.

Right, we don't do that anywhere?

I'm not sure I understand your example, you've defined a group and members of the group in one resource?
And then what is happening in `test_group_members`?

**Comment by hmlanigan** [comment]
Approving the schema after discussions with author
