### ISSUE TITLE
Terraform 0.13.0 takes 15 times longer time to run apply than 0.12.0

### ISSUE THREAD

**Issue by dparv** [juju/terraform-provider-juju#535]
### Description

Seems 0.13.0 is now waiting on application to get deployed and doesn't move forward with all the changes to be applied on a controller, this way there is way less concurrency from juju's side, making the deployment way slower. With 0.12.0 the pipeline completed within 1-2 minutes, leaving juju to execute until all charms are active/idle, now with 0.13.0, took 16 min, seems it's waiting for some applications to be deployed in a (random?) order and not allowing others to execute at the same time, prolonging deployments with a lot of different applications, e.g. kubeflow.

### Urgency

Annoying bug in our test suite

### Terraform Juju Provider version

0.13.0

### Terraform version

1.7.4

### Juju version

3.4.4

### Reproduce / Test

```shell
terraform apply
```

### Debug/Panic Output

```shell
0.12.0 pipeline run took 1m 32s -> https://pastebin.canonical.com/p/cGqRyQWyFj/ 
0.13.0 pipeline took 16m 28s -> https://pastebin.canonical.com/p/GmYzyc66ct/
```

**Comment by anvial** [comment]
Hey,

I suppose this is not a bug; this is because we made some of the attributes "compute", and to define the state, terraform waits till the result of their deployment.

So looks like this is how it works right now.

**Comment by dparv** [comment]
@anvial not a bad thing, but we are loosing a lot of concurrency with this - if tf has to wait I am +1 on this, but it would be good to dump all the terraform models, applications and relations in a single batch, then wait for the specific things to complete, now what happens is e.g. 1/3 of apps is deployed, then the next app has storage, tf waits for that, after 2-3 minutes continue with the second 2/3 of apps, hits another app that has storage, waits, etc. So this prolongs execution and we are losing the parallelism which juju is great at.

**Comment by gboutry** [comment]
Terraform basically generates a DAG and waits for each node of the dag to be completed before moving forward, applying parallelism where it can. Previously, a resource was considered created almost immediately, without much waiting.
A way to alleviate this pain could be to process more resources in parallel: `terraform apply -parallelism 15` (default is 10), but this works only if the resource dependency graph allows it.

**Comment by dparv** [comment]
I think a graph depth walk of 10 levels is quite enough for juju dependencies - e.g. the only dependencies now are storage constraints, as before everything was dumped in the model immediately. So I would assume that workflow can be: dump everything in the model that doesn't have storage first and then wait for the rest of the applications with storage that needs to be created, this was way I think the execution will be much faster.

**Comment by dparv** [comment]
@hmlanigan which release is this fix targeting?
