### ISSUE TITLE
Schema: Add UUID to application offer resource

### ISSUE THREAD

**Issue by kian99** [juju/terraform-provider-juju#583]
### Requirements

# Type of change
Changing existing schema

# Description
I found that the Juju names package changed in v4->v5 from accepting an offer URL to accepting an offer UUID. For the purposes of JAAS and it's generic access methods, we use juju tags to communicate permissions over the wire. Because of this we will need to hold on the Juju names/v4 package until the provider stores offer UUIDs.

Currently the provider does not store the UUID although it can be obtained via a call to Juju's `GetConsumeDetails` method. I've also checked and confirmed that [Juju 2.9](https://github.com/juju/juju/blob/2.9/rpc/params/crossmodel.go#L74) and 3.x both contain app offer UUID.

With the addition of the offer UUID we can eliminate any need for names/v4.

# Details
The current offer resource already stores the offer URL in the `id` field so I'd propose a separate field for the offer UUID.

```
"uuid": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
```

### Urgency

It would save from a weird workaround

**Comment by hmlanigan** [comment]
It looks like GetConsumeDetails is the only API call which has the OfferUUID in the input or result data. This will mean intrusive changes to ensure that the UUID is always read and written.

This is horrid to have to work around as the Juju ApplicationOffers API does not talk in Offer UUIDs. How is that handled on the JAAS side as you can't ask Juju to provide an offer based off UUID.
