### ISSUE TITLE
Allow for model uuids to be used with resources

### ISSUE THREAD

**Issue by hmlanigan** [juju/terraform-provider-juju#596]
### Type of change

Changing existing schema

### Description

Add uuid as a computed value of the juju_model resource, it's already available for datasource juju_model. Then allow the model attribute to be a uuid or a name in other juju resources. With name being deprecated. This will allow for removing the model uuid cache, facilitate fixing #504 and encouraging best practices with terraform.

### Details

``` diff
diff --git a/internal/provider/resource_model.go b/internal/provider/resource_model.go
@@ -73,6 +74,13 @@ func (r *modelResource) Schema(_ context.Context, _ resource.SchemaRequest, resp
                                        stringplanmodifier.RequiresReplace(),
                                },
                        },
+                       "uuid": schema.StringAttribute{
+                               Description: "The uuid of the model",
+                               Computed:    true,
+                               PlanModifiers: []planmodifier.String{
+                                       stringplanmodifier.UseStateForUnknown(),
+                               },
+                       },
```

The description of "model" for all other resources having on, would be along the lines of:
``` diff
@@ -109,8 +109,9 @@ func (r *machineResource) Schema(_ context.Context, req resource.SchemaRequest,
                                },
                        },
                        ModelKey: schema.StringAttribute{
-                               Description: "The Juju model in which to add a new machine.",
-                               Required:    true,
+                               Description: "The uuid of the Juju model in which to add a new machine. Use of the model name is DEPRECATED," +
+                                       " though still allowed. Support for use of model name will be removed at a future date.",
+                               Required: true,
                                PlanModifiers: []planmodifier.String{
                                        stringplanmodifier.RequiresReplace(),
                                },
```

### Example terraform plan

``` terraform
resource "juju_model" "model" {
  name = "testmodel"
}

resource "juju_application" "application" {
  name = "my-application"

  model = juju_model.model.uuid

  charm {
    name     = "ubuntu"
    channel  = "edge"
    revision = 24
  }
}
```

**Comment by kian99** [comment]
This looks like a good middleground between using model names vs model UUIDs.

When we implement this change I'd also like us to consider whether we can disambiguate model names by providing the model owner in queries, fully resolving https://github.com/juju/terraform-provider-juju/issues/504 even in cases where a model name is used. E.g. When a model name is detected we could assume the model owner is the user making the Juju connection. Though we should verify that assumption with some existing places where the provider is used. If that assumption is faulty then we can keep the existing behaviour as is.

**Comment by hmlanigan** [comment]
This change deprecate model names from non model resources, thus it's not worth the effort to do handle combined owner/model names for juju_model resources in #504. Doing so will also encourage behavior we're trying to avoid. We want the resources to be linked with dependencies. 

You can add "owner" to the juju_model datasource and update that to find the model uuid based off the model name and owner. You'd want to use the data source in the scenario in #504, you're using a model which has already been create. The juju_model resource assume the current user owns and creates the model.

**Comment by nvinuesa** [comment]
Approved.
