### ISSUE TITLE
Schema: JAAS group data source

### ISSUE THREAD

**Issue by pkulik0** [juju/terraform-provider-juju#604]
### Type of change

Adding new schema

### Description

This schema change is needed for implementation of a data source for JAAS groups. We already have a resource for them and the schema attributes are exactly the same.

### Details

```go
"name": schema.StringAttribute{
	Description: "The name of the group.",
	Required:    true,
},
"uuid": schema.StringAttribute{
        Description: "The UUID of the group.",
	Computed:    true,
},
```

The JAAS group resource takes a name to create a group, so for ease of use this data source also takes in the attribute already known to users and fetches the UUID from JAAS.

### Example terraform plan

```terraform
resource "juju_jaas_group" "test" {
  name = "group-0"
}

// --------------- Second plan that uses the data source to use the group from plan #1

data "juju_jaas_group" "test" {
  name = "group-0"
}
```

**Comment by kian99** [comment]
Thanks for this, looks good to me.

**Comment by hmlanigan** [comment]
Approved.
