### ISSUE TITLE
Questions about this project 

### ISSUE THREAD

**Issue by Houzonglaile** [juju/terraform-provider-juju#623]
Is the 'terraform-provider-juju' project use terraform template file (.yml) to deploy JUJU? And what is the connection and relation between 'terraform-provider-juju' project and 'python-libjuju' project? Are they both simply a method to deploy JUJU projects? Developers use either terroaform or python to use JUJU to deploy their projects on cloud, am I correct?

**Comment by Aflynn50** [comment]
Hey Houzonglaile, a Juju controller can be bootstrapped on a cloud, the controller can then be connected to with a juju client. These clients include the juju cli, terraform provider (for use with terraform plans) and pylibjuju (a python client). 

See the clients page on the docs for more: https://juju.is/docs/juju/client

The easiest way to get started with Juju is using the Juju cli and following this tutorial: https://juju.is/docs/juju/tutorial

We also have a matrix channel which is good for asking questions if you want a quicker response. It'd be great to see you there!
https://matrix.to/#/#charmhub-juju:ubuntu.com
