### ISSUE TITLE
uing snap install juju clieant，then tip error：snap no fund

### ISSUE THREAD

**Issue by bestshenzhen** [juju/terraform-provider-juju#626]
### Description

uing snap install juju clieant，then tip error：snap no fund

### Urgency

Casually reporting

### Terraform Juju Provider version

juju3.6

### Terraform version

juju3.6

### Juju version

juju3.6

### Terraform Configuration(s)

```terraform
uing snap install juju clieant，then tip error：snap no fund
```

### Reproduce / Test

```shell
uing snap install juju clieant，then tip error：snap no fund
```

### Debug/Panic Output

```shell
uing snap install juju clieant，then tip error：snap no fund
```

### Notes & References

uing snap install juju clieant，then tip error：snap no fund

**Comment by jack-w-shaw** [comment]
Hi @bestshenzhen 

Could you re-write this bug please? And fill out the required fields as well please.
